---
title: "Analyzing Levesque’s data"
author: "Leonor Schubert"
date: "14 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, message=FALSE}
library('SingleCellExperiment')
library('DropletUtils')
library('scater')
#library('scuttle')
# scater, scran, uwot

```

```{r readData}
# set local path
local.path <- getwd()
setwd(local.path)
patient1_HS.path <- file.path("data", "patient1_HS")

# read in unfiltered data
fname <- file.path(patient1_HS.path, "outs/raw_feature_bc_matrix")
sce.patient1_HS <- read10xCounts(fname, col.names=TRUE)

# rename genes
rownames(sce.patient1_HS) <- uniquifyFeatureNames(rowData(sce.patient1_HS)$ID, rowData(sce.patient1_HS)$Symbol)

# put antibody data in seperate summarizedExperiment inside our singleCellExperiment
sce.patient1_HS <- splitAltExps(sce.patient1_HS, rowData(sce.patient1_HS)$Type)
# altExp(sce.patient1_HS)

# from sparse to normal matrix for downstream analysis
counts(altExp(sce.patient1_HS)) <- as.matrix(counts(altExp(sce.patient1_HS)))

```

```{r qualityControl_Antibodies}
# remove cells that have failed to capture/sequence antibodies, remove cells that have unusually low numbers antibodies (less than or equal to half of the total number of tags)
df.ab.patient1_HS <- perCellQCMetrics(altExp(sce.patient1_HS))

# exclude antibodies with zero counts across all cells
number.nonzero.patient1_HS <- sum(!rowAlls(counts(altExp(sce.patient1_HS)), value=0L))
discard.ab.patient1_HS <- df.ab.patient1_HS$detected <= number.nonzero.patient1_HS/2
summary(discard.ab.patient1_HS)

# distribution of the number of detected antibodies across all cells, redline=threshold, below cells are discarded (looks like almost all?)
hist(df.ab.patient1_HS$detected, col='grey', main="", xlab="Number of detected Antibody-tags") + abline(v=number.nonzero.patient1_HS/2, col="red", lty=2)

## Should we really discard all these cells (732648), would only keep 4632?
## I wouldn't think so, but in the pipeline in the bioconductor this is what would be done...
```

```{r qualityControl_emptyDroplets}
# using emptyDrops
set.seed(11)

# use emptyDrops algorithm to predict which cells are probably empty
e.out.patient1_HS <- emptyDrops(counts(sce.patient1_HS), niters = 10000, test.ambient=TRUE)

# look at sum summary statistics (non-significant & limited field should be 0, otherwise ran emptyDrops again with higher niters)
summary(e.out.patient1_HS$FDR <= 0.001)
table(Sig=e.out.patient1_HS$FDR <= 0.001, Limited=e.out.patient1_HS$Limited)

# should have an approx. uniform distribution, especially at the beginning (if high peaks there, decrease lower in emptyDrops)
hist(e.out.patient1_HS$PValue[e.out.patient1_HS$Total <= limit & e.out.patient1_HS$Total > 0],
    xlab="P-value", main="", col="grey80")

# subset sce
sce.patient1_HS <- sce.patient1_HS[, which(e.out.patient1_HS$FDR <= 0.001)]
```

```{r qualityControl_deadCells}
# discard dead cells by looking at where there's high percentage of mitochondrial RNA
mito <- grep("^MT-", rowData(sce.patient1_HS)$Symbol)
df.mito.patient1_HS <- perCellQCMetrics(sce.patient1_HS, subsets=list(Mito=mito))
discard.mito.patient1_HS <- isOutlier(df.mito.patient1_HS$subsets_Mito_percent, type="higher")

# looks like quite a lot of cells?
summary(discard.mito.patient1_HS)

plot(df.mito.patient1_HS$sum, df.mito.patient1_HS$subsets_MT_percent, log="x",
    xlab="Total count", ylab='Mitochondrial %') + abline(h=attr(discard.mito.patient1_HS, "thresholds")["higher"], col="red")
```
